# Generated by Django 5.0 on 2026-01-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Platform name (e.g., Instagram, Facebook, YouTube)', max_length=50, unique=True)),
                ('icon_url', models.URLField(help_text='URL to the icon/image for this social media platform')),
                ('profile_url', models.URLField(help_text='URL to your social media profile')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Social Media',
                'ordering': ['order', 'name'],
            },
        ),
    ]
