# Generated by Django 5.0 on 2026-01-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='facebook_reel_url',
            field=models.URLField(blank=True, help_text='Facebook Reel embed URL', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='instagram_reel_url',
            field=models.URLField(blank=True, help_text='Instagram Reel embed URL', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='YouTube video or Shorts URL', null=True),
        ),
    ]
