# Generated by Django 5.0 on 2026-01-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_facebook_reel_url_product_instagram_reel_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='contact@mrdspstore.com', help_text='Contact email address displayed on About page', max_length=254)),
                ('contact_phone', models.CharField(default='+1 (234) 567-890', help_text='Contact phone number displayed on About page', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
