# Generated by Django 5.0 on 2026-01-11 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='facebook_reel_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='instagram_reel_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='youtube_video_url',
        ),
        migrations.CreateModel(
            name='ProductSocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(help_text='Platform name (e.g., Instagram, YouTube, Facebook, TikTok)', max_length=50)),
                ('url', models.URLField(help_text='URL to the social media content (reel, video, etc.)')),
                ('description', models.CharField(blank=True, help_text='Short description of the content', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_links', to='products.product')),
            ],
            options={
                'ordering': ['order', 'platform_name'],
                'unique_together': {('product', 'platform_name', 'url')},
            },
        ),
    ]
