# Generated by Django 5.0 on 2026-01-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_facebook_reel_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='page_size',
            field=models.IntegerField(default=3, help_text='Number of products to display per page (used by frontend pagination)'),
        ),
    ]
