# Generated by Django 5.0 on 2026-01-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_sitesettings_page_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='operating_hours',
            field=models.CharField(default='07:00 AM - 07:00 PM', help_text="Operating hours displayed in header (e.g., '07:00 AM - 07:00 PM')", max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='contact@mrd sphub.com', help_text='Contact email address displayed on About page', max_length=254),
        ),
    ]
