# Generated by Django 5.0 on 2026-01-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_sitesettings_operating_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='brand_name',
            field=models.CharField(default='MrDSP Hub', help_text='Brand/Company name displayed throughout the site', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='All Rights Reserved.', help_text="Copyright text displayed in footer (e.g., 'All Rights Reserved.')", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description',
            field=models.TextField(default='Your trusted destination for premium product reviews and exclusive deals.', help_text='Brand description displayed in footer and about sections'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='developer_credit',
            field=models.CharField(blank=True, help_text="Developer credit text (e.g., 'Developed By Opulent Multimedia')", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='developer_credit_url',
            field=models.URLField(blank=True, help_text='URL for developer credit link (optional)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_logo_url',
            field=models.URLField(blank=True, help_text='URL to footer logo image (optional, falls back to logo_url if not set)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to header logo image (AWS S3, Cloudinary, Imgur, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='Premium Picks', help_text='Brand tagline displayed in headers and footers', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_url',
            field=models.URLField(blank=True, help_text='WhatsApp contact URL (e.g., https://wa.me/1234567890 or https://api.whatsapp.com/send?phone=1234567890)', null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='contact@mrdsphub.com', help_text='Contact email address displayed on About page', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='+91 9876543210', help_text='Contact phone number displayed on About page', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='page_size',
            field=models.IntegerField(default=30, help_text='Number of products to display per page (used by frontend pagination)'),
        ),
    ]
