# Generated by Django 5.0 on 2026-01-12 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20260112_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tenant name (e.g., 'MrDSP Hub', 'Client Name')", max_length=100, unique=True)),
                ('subdomain', models.SlugField(blank=True, help_text="Subdomain for this tenant (e.g., 'mrdsphub' for mrdsphub.mrdsphub.com). Leave blank for main domain.", null=True, unique=True)),
                ('domain', models.CharField(blank=True, help_text="Custom domain for this tenant (e.g., 'mrdsphub.com'). Leave blank to use subdomain.", max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tenant is active')),
                ('is_default', models.BooleanField(default=False, help_text='Default tenant for requests without subdomain/domain match')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_backend',
            field=models.CharField(blank=True, help_text='Email backend (e.g., django.core.mail.backends.smtp.EmailBackend). Falls back to .env EMAIL_BACKEND if not set.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_from_address',
            field=models.EmailField(blank=True, help_text='Email address to send emails from (e.g., noreply@mrdsphub.com). Falls back to .env DEFAULT_FROM_EMAIL if not set.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host',
            field=models.CharField(blank=True, help_text='SMTP host (e.g., smtp.gmail.com). Falls back to .env EMAIL_HOST if not set.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_port',
            field=models.IntegerField(blank=True, help_text='SMTP port (e.g., 587). Falls back to .env EMAIL_PORT if not set.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='Use SSL for email. Falls back to .env EMAIL_USE_SSL if not set.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS for email. Falls back to .env EMAIL_USE_TLS if not set.'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(help_text='Platform name (e.g., Instagram, Facebook, YouTube)', max_length=50),
        ),
        migrations.AddField(
            model_name='badge',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this badge belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='products.tenant'),
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this category belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.tenant'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this chat message belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='products.tenant'),
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this product belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.tenant'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tenant',
            field=models.OneToOneField(blank=True, help_text='Tenant these settings belong to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to='products.tenant'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this social media belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='products.tenant'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant this activity belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='products.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tenant', 'name'), ('tenant', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='socialmedia',
            unique_together={('tenant', 'name')},
        ),
    ]
