# Generated by Django 5.0 on 2026-01-12 09:43

from django.db import migrations


def create_default_tenant_and_assign_data(apps, schema_editor):
    """Create default tenant and assign all existing data to it"""
    Tenant = apps.get_model('products', 'Tenant')
    Category = apps.get_model('products', 'Category')
    Badge = apps.get_model('products', 'Badge')
    Product = apps.get_model('products', 'Product')
    SocialMedia = apps.get_model('products', 'SocialMedia')
    SiteSettings = apps.get_model('products', 'SiteSettings')
    UserActivity = apps.get_model('products', 'UserActivity')
    ChatMessage = apps.get_model('products', 'ChatMessage')
    
    # Create default tenant
    default_tenant, created = Tenant.objects.get_or_create(
        name="Default Tenant",
        defaults={
            'is_default': True,
            'is_active': True,
        }
    )
    
    if created:
        print(f"Created default tenant: {default_tenant.name}")
    else:
        # Ensure it's marked as default
        default_tenant.is_default = True
        default_tenant.is_active = True
        default_tenant.save()
        print(f"Using existing tenant: {default_tenant.name}")
    
    # Assign all existing data to default tenant
    Category.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    Badge.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    Product.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    SocialMedia.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    UserActivity.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    ChatMessage.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    
    # Handle SiteSettings - migrate existing settings to default tenant
    old_settings = SiteSettings.objects.filter(tenant__isnull=True).first()
    if old_settings:
        # Create new SiteSettings for default tenant with existing data
        SiteSettings.objects.get_or_create(
            tenant=default_tenant,
            defaults={
                'brand_name': old_settings.brand_name,
                'tagline': old_settings.tagline,
                'description': old_settings.description,
                'logo_url': old_settings.logo_url,
                'footer_logo_url': old_settings.footer_logo_url,
                'copyright_text': old_settings.copyright_text,
                'developer_credit': old_settings.developer_credit,
                'developer_credit_url': old_settings.developer_credit_url,
                'contact_email': old_settings.contact_email,
                'contact_phone': old_settings.contact_phone,
                'operating_hours': old_settings.operating_hours,
                'whatsapp_url': old_settings.whatsapp_url,
                'page_size': old_settings.page_size,
            }
        )
        # Delete old settings
        old_settings.delete()
    else:
        # Create new SiteSettings for default tenant
        SiteSettings.objects.get_or_create(tenant=default_tenant)
    
    print(f"Assigned all existing data to tenant: {default_tenant.name}")


def reverse_migration(apps, schema_editor):
    """Reverse migration - remove tenant assignments"""
    # This is a one-way migration, but we provide a reverse function
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_tenant_sitesettings_email_backend_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_tenant_and_assign_data, reverse_migration),
    ]
