# Generated by Django 5.0

from django.db import migrations, models
import django.db.models.deletion


def ensure_all_data_has_tenant(apps, schema_editor):
    """Ensure all data has a tenant assigned (safety check)"""
    Tenant = apps.get_model('products', 'Tenant')
    Category = apps.get_model('products', 'Category')
    Badge = apps.get_model('products', 'Badge')
    Product = apps.get_model('products', 'Product')
    SocialMedia = apps.get_model('products', 'SocialMedia')
    SiteSettings = apps.get_model('products', 'SiteSettings')
    UserActivity = apps.get_model('products', 'UserActivity')
    ChatMessage = apps.get_model('products', 'ChatMessage')
    
    # Get default tenant
    default_tenant = Tenant.objects.filter(is_default=True).first()
    if not default_tenant:
        default_tenant = Tenant.objects.first()
    
    if not default_tenant:
        raise ValueError("No tenant found! Please create a tenant first.")
    
    # Ensure all data has tenant
    Category.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    Badge.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    Product.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    SocialMedia.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    UserActivity.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    ChatMessage.objects.filter(tenant__isnull=True).update(tenant=default_tenant)
    
    # Ensure SiteSettings has tenant
    SiteSettings.objects.filter(tenant__isnull=True).delete()  # Delete orphaned settings
    SiteSettings.objects.get_or_create(tenant=default_tenant)
    
    print(f"Ensured all data has tenant: {default_tenant.name}")


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_assign_default_tenant'),
    ]

    operations = [
        migrations.RunPython(ensure_all_data_has_tenant, migrations.RunPython.noop),
        # Make tenant fields non-nullable
        migrations.AlterField(
            model_name='badge',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this badge belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='badges',
                to='products.tenant'
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this category belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='categories',
                to='products.tenant'
            ),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this chat message belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='chat_messages',
                to='products.tenant'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this product belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products',
                to='products.tenant'
            ),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tenant',
            field=models.OneToOneField(
                help_text='Tenant these settings belong to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='site_settings',
                to='products.tenant'
            ),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this social media belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='social_media',
                to='products.tenant'
            ),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='tenant',
            field=models.ForeignKey(
                help_text='Tenant this activity belongs to',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_activities',
                to='products.tenant'
            ),
        ),
    ]
