# Generated by Django 5.0 on 2026-03-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_make_tenant_fields_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email_from_address',
            field=models.EmailField(blank=True, help_text='Email address to send emails from (e.g., noreply@mrdsphub.com). Falls back to tenant contact_email (and then a safe default) if not set.', max_length=254, null=True),
        ),
    ]
