# Generated by Django 5.0 on 2026-03-25 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_affiliate_store_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True)),
                ('excerpt', models.TextField(blank=True, default='')),
                ('content', models.TextField()),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('author_name', models.CharField(blank=True, default='', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category for internal linking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='products.category')),
                ('tenant', models.ForeignKey(help_text='Tenant this blog post belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='products.tenant')),
            ],
            options={
                'ordering': ['-published_at', '-updated_at'],
                'unique_together': {('tenant', 'slug')},
            },
        ),
    ]
