# Generated by Django 5.0 on 2026-03-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='recommended_product_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of Product.admin_number values to show as recommended products for this blog post (order preserved).'),
        ),
        migrations.AddField(
            model_name='product',
            name='admin_number',
            field=models.PositiveIntegerField(blank=True, help_text='Admin number used for blog recommended products selection', null=True),
        ),
    ]
