# Generated by Django 5.0 on 2026-03-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_blogpost_recommended_product_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='recommended_product_numbers',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of Product serial numbers to show as recommended products for this blog post (order preserved).', verbose_name='Recommended product serial numbers'),
        ),
        migrations.AlterField(
            model_name='product',
            name='admin_number',
            field=models.PositiveIntegerField(blank=True, help_text='Serial number used by blog “Recommended products” selection (in order).', null=True, verbose_name='Serial number'),
        ),
    ]
