# Generated by Django 5.0 on 2026-03-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_blogpost_recommended_product_numbers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cta_label',
            field=models.CharField(blank=True, default='', help_text='Optional blog CTA button text (e.g., Buy Now on Amazon).', max_length=80),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_product_serial_number',
            field=models.PositiveIntegerField(blank=True, help_text='Optional product serial number to auto-resolve CTA URL from product affiliate link.', null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cta_url',
            field=models.URLField(blank=True, help_text='Optional direct CTA URL. Leave blank to use CTA Product Serial Number.', null=True),
        ),
    ]
